%% SETUP GLOBAL VARS

RSTRUCT_OR_K = 10 ;
W_DIST = 'exp' ; 
E_DIST = 'poisson' ;
WSBM_NUM_TRIAL = 20 ;
WSBM_ALPHA = 0.5 ;
WSBM_MAIN_ITER = 500 ;
WSBM_MU_ITER = 250 ;
WSBM_MAINTOL = 0.01 ;
WSBM_MUTOL = 0.01 ;

% set the opts
% wsbmModelInputs = { RSTRUCT, ... 
%     'W_Distr', W_DIST, ...
%     'E_Distr', E_DIST, ...
%     'numTrials',WSBM_NUM_TRIAL,...
%     'alpha', WSBM_ALPHA, ...
%     'mainMaxIter', WSBM_MAIN_ITER , ...
%     'muMaxIter' , WSBM_MU_ITER,...
%     'mainTol',WSBM_MAINTOL, ...
%     'muTol', WSBM_MUTOL ,...
%     'verbosity', 0};

outStr = '' ;
save([ outStr 'vars.mat'],'*') ;